### ISSUE TITLE
Error: Failed to instantiate provider "helmfile" to obtain schema: fork/exec terraform.d/plugins/darwin_amd64: exec format error

### ISSUE THREAD

**Issue by abdennour** [mumoshu/terraform-provider-helmfile#18] opened 2020-07-18 09:09 UTC
The same issue #15 

Please try to **reproduce** the issue before **closing** it.

I am still not able to get it work

**Comment by mumoshu** [comment] 2020-07-18 09:39
@abdennour I did try to reproduce it and couldn't replicate your issue. And it would be great if you could understand that I'm always trying my best, even though I'm not even paid 1 cent for a bunch of my OSS works. 

Also, please forgive me closing "question" issues once answered, as "so many people leave answered issues open". If I don't close it myself, there will easily hundreds of answered issues open, which hurts my productivity.

Anyway, reading the error message, your issue seems like more like due to that you're using macOS build of the provider even though you're using another OS.

Grab the correct binary for your OS and the arch from https://github.com/mumoshu/terraform-provider-helmfile/releases and replace `darwin_amd64` part of the path with correct `os_arch`, like `linux_amd64` if that's your os and arch.

I believe this is a question rather than a bug, so I'm closing this as answered. But please feel free to reopen if necessary.

**Closed by mumoshu** 2020-07-18 09:39 UTC

**Comment by mumoshu** [comment] 2020-07-18 09:45
@abdennour FYI, https://support.hashicorp.com/hc/en-us/articles/360016992613-Using-custom-and-community-providers-in-Terraform-Cloud-and-Enterprise can be a good read for installing custom providers.

**Comment by abdennour** [comment] 2020-07-18 11:06
@mumoshu  totally agree !  Thank you so much.
